# Generated by Django 4.2 on 2023-04-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PathLabTestBooking',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(default='', max_length=50)),
                ('booking_date', models.DateField()),
                ('test_result_url', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(default='9876543210', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathlab_bookings', to='patients.patient')),
            ],
        ),
    ]
