# Generated by Django 4.2 on 2023-04-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otherusers', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_available', models.CharField(choices=[('available', 'Available'), ('not vailable', 'Not Available')], default='available', max_length=20)),
                ('evening_available', models.CharField(choices=[('available', 'Available'), ('not vailable', 'Not Available')], default='available', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='otherusers.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('timing', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
