# Generated by Django 4.2 on 2023-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timing',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='morning', max_length=20),
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
