# Generated by Django 4.2 on 2023-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=50)),
                ('specification', models.TextField()),
                ('doctor_email', models.CharField(max_length=50)),
                ('doctor_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('specification', models.TextField()),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
