# Generated by Django 4.2 on 2023-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherusers', '0002_doctor_evening_available_doctor_morning_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='evening_available',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='morning_available',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=20),
        ),
    ]
